### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by kumosal** [benmanu/silverstripe-skeleton#1]
Hello,

First, thank you for sharing this helpful Silverstripe skeleton.

I followed your installation steps until running "yarn run dev".  My browser then shows this error: "SilverStripe Framework requires a $databaseConfig defined." I went through the code and I notice the absence of "my_site" folder with its _config file. I thought maybe I should write my own, so I copied my_site folder from a SS install zip file, updated the $databaseConfig variable but I still get the same error. Am I missing something here?

Thanks

**Comment by benmanu** [comment]
Hey @kumosal, I think you've spotted the problem, what's missing is both an `_ss_environment.php` file in either the root of your site or your server, and the `_config.php` file. I'll add both as todo tasks for the base project, will definitely be useful!

In the mean time I've included a boilerplate that I run with locally (some details redacted), and some more info about it can be found in the [SilverStripe docs](https://docs.silverstripe.org/en/3/getting_started/environment_management/).

Let me know if you run into any other issues, always a work in progress so any feedback is welcome, thanks.

**_ss_environment.php**
```
<?php

/*---------------------------------------------------------------------------------
 * Set environment type
 *
 * Options: dev, test, live
 *--------------------------------------------------------------------------------*/
define('SS_ENVIRONMENT_TYPE', 'dev');

/*---------------------------------------------------------------------------------
 * Setup database details
 *--------------------------------------------------------------------------------*/
define('SS_DATABASE_SERVER', 'localhost');
define('SS_DATABASE_USERNAME', 'root');
define('SS_DATABASE_PASSWORD', 'root');
define('SS_DATABASE_NAME', '{your db name}');

/*---------------------------------------------------------------------------------
 * Default CMS User
 *--------------------------------------------------------------------------------*/
define('SS_DEFAULT_ADMIN_USERNAME', 'admin');
define('SS_DEFAULT_ADMIN_PASSWORD', 'password');

// Protect entire site by basic auth when set to true
define('SS_USE_BASIC_AUTH', false);


/*---------------------------------------------------------------------------------
 * Email
 *
 * This ensures emails are only sent to you and not actual email addresses.
 *--------------------------------------------------------------------------------*/
define('SS_SEND_ALL_EMAILS_TO', '{your email}');
define('SS_SEND_ALL_EMAILS_FROM', '{your email}');

// This is used by sake to know which directory points to which URL
global $_FILE_TO_URL_MAPPING;
$_FILE_TO_URL_MAPPING['/var/www/public'] = '{your site URL}';
```

**mysite/_config.php**
```
global $project;
$project = 'mysite';

global $database;
$database = '';

require_once('conf/ConfigureFromEnv.php');
```

**Comment by kumosal** [comment]
yes, I got working now.. thanks
